before_script:
  - echo "Before script"
  - cd /var/www/apusds_dev/
building:
  stage: build
  script:
    - git reset --hard
    - git pull origin master
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chown -R deployer:www-data /var/www/apusds_dev/
    - find /var/www/apusds_dev -type f -exec chmod 664 {} \;
    - find /var/www/apusds_dev -type d -exec chmod 775 {} \;
    - chgrp -R www-data storage bootstrap/cache
    - chmod -R ug+rwx storage bootstrap/cache
testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
    - php artisan queue:restart #if you use queue
